version: '2'
services:
  web:
    restart: always
    build:
     context: .
     dockerfile: Dockerfile-production
    container_name: construction-chemicals
    ports:
     - "3001:3000"
    environment:
     - NODE_ENV=production
