version: '2'
services:
  web:
    restart: always
    build: .
    container_name: construction-chemicals
    ports:
     - "3000:3000"
     - "5858:5858"
     - "8080:8080"
     - "35729:35729"
    environment:
     - NODE_ENV=development
